//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20180417_WCF_HistoricalEventsServiceClient.RemoteHistoricalEvents {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteHistoricalEvents.IHistoricalEvents")]
    public interface IHistoricalEvents {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalEvents/TestConnection", ReplyAction="http://tempuri.org/IHistoricalEvents/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalEvents/TestConnection", ReplyAction="http://tempuri.org/IHistoricalEvents/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalEvents/InfoAboutEvents", ReplyAction="http://tempuri.org/IHistoricalEvents/InfoAboutEventsResponse")]
        _20180417_WCF_HistoricalEventsServiceLib.CalendarOfEvents[] InfoAboutEvents(System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalEvents/InfoAboutEvents", ReplyAction="http://tempuri.org/IHistoricalEvents/InfoAboutEventsResponse")]
        System.Threading.Tasks.Task<_20180417_WCF_HistoricalEventsServiceLib.CalendarOfEvents[]> InfoAboutEventsAsync(System.DateTime startDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoricalEventsChannel : _20180417_WCF_HistoricalEventsServiceClient.RemoteHistoricalEvents.IHistoricalEvents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoricalEventsClient : System.ServiceModel.ClientBase<_20180417_WCF_HistoricalEventsServiceClient.RemoteHistoricalEvents.IHistoricalEvents>, _20180417_WCF_HistoricalEventsServiceClient.RemoteHistoricalEvents.IHistoricalEvents {
        
        public HistoricalEventsClient() {
        }
        
        public HistoricalEventsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoricalEventsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoricalEventsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoricalEventsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public _20180417_WCF_HistoricalEventsServiceLib.CalendarOfEvents[] InfoAboutEvents(System.DateTime startDate) {
            return base.Channel.InfoAboutEvents(startDate);
        }
        
        public System.Threading.Tasks.Task<_20180417_WCF_HistoricalEventsServiceLib.CalendarOfEvents[]> InfoAboutEventsAsync(System.DateTime startDate) {
            return base.Channel.InfoAboutEventsAsync(startDate);
        }
    }
}
